from abc import ABC, abstractmethod
from dataclasses import dataclass

@dataclass
class BaseState:
    """
    Base class for holding the internal persistent state of a simulation module.
    """
    pass

@dataclass
class BaseInput:
    """
    Base class for defining the required input signals for a module's update cycle.
    """
    pass

@dataclass
class BaseOutput:
    """
    Base class for the processed results generated by a module after an update.
    """
    pass

class BaseModule(ABC):
    """
    Abstract base class that defines the lifecycle and interface for all vehicle subsystems.
    """
    def __init__(self):
        """
        Initializes the module with a default state placeholder.
        """
        self.state = None

    @abstractmethod
    def update(self, dt: float):
        """
        Processes physics and logic for the given time step. Must be implemented by subclasses.
        """
        pass

    @abstractmethod
    def apply_config(self, config):
        """
        Configures the module parameters using a specific specification object.
        """
        pass